# Student makefile for the Hello Lab
javac: 
	javac -cp .:./junit.jar:./hamcrest-core-1.3.jar TestRunner.java TestJUnit.java ContactsManager.java


java:
	java -cp .:./junit.jar:./hamcrest-core-1.3.jar TestRunner

clean:
	rm -rf *~ ContactManager
